// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"
	"simplerick/internal"
	"simplerick/internal/discord"
	"simplerick/webhooks/github"
	"simplerick/webhooks/sentry"
)

// Injectors from wire.go:

func setupApplication(ctx context.Context) (application, error) {
	executor := discord.ProvideExecutor()
	githubWebhookConfig, err := internal.ProvideGithubWebhookConfig()
	if err != nil {
		return application{}, err
	}
	webhookHandler := github.ProvideWebhookHandler(executor, githubWebhookConfig)
	sentryWebhookConfig, err := internal.ProvideSentryWebhookConfig()
	if err != nil {
		return application{}, err
	}
	sentryWebhookHandler := sentry.ProvideWebhookHandler(executor, sentryWebhookConfig)
	router := newRouter(webhookHandler, sentryWebhookHandler)
	mainApplication := newApplication(router)
	return mainApplication, nil
}
