name: ci

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.meta.outputs.tags[0] }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/bf3rm/simplerick
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: sagebind/docker-swarm-deploy-action@v2
        with:
          remote_host: ${{ secrets.DOCKER_HOST }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          args: service update --image ghcr.io/bf3rm/simplerick:${{ needs.publish.outputs.version }} ${{ secrets.DOCKER_SERVICE_NAME }}